/*
 * Generated by XDoclet - Do not edit!
 */
package com.opensymphony.workflow.ejb;

/**
 * Home interface for Workflow.
 * @author <a href="mailto:plightbo@hotmail.com">Pat Lightbody</a>
 * @author <a href="mailto:hani@formicary.net">Hani Suleiman</a>
 * @version $Revision: 1.7 $
 */
public interface WorkflowHome
   extends javax.ejb.EJBHome
{
   //public static final String COMP_NAME="java:comp/env/ejb/Workflow";
   //public static final String JNDI_NAME="Workflow";

   public com.opensymphony.workflow.ejb.WorkflowRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
